apiVersion: v1
kind: Pod
metadata:
  name: attack-http-api
  namespace: my-namespace
  labels:
    app: attack-http-api
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: [ "sh", "-c", "--" ]
    args: [ "while true; do curl -I  https://dog.ceo/api/breeds/image/random; sleep 1;done;" ]
#  imagePullSecrets:
#  - name: my-repository-cred
